### ISSUE TITLE
Tried to clone but no content

### ISSUE THREAD

**Issue by richpsharp** [rmgriffin/Portfolio-LB#1]
Hi, I was trying to clone this project for my own research but there is no content in it so it didn't let me clone. I would put in a pull request to add content but there is no content to merge into. Here's some information about that: https://en.wikipedia.org/wiki/Chicken_or_the_egg

**Comment by rmgriffin** [comment]
Locate the "merge simpson" button on your console and select that and see if anything happens

**Comment by richpsharp** [comment]
Tried that but it only downloaded some other guy's life goal?

![image](https://user-images.githubusercontent.com/7773490/218230516-df836e58-2db8-446d-8c3f-1cca2d935ead.png)

**Comment by rmgriffin** [comment]
Content with content
